// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2OY3bdgszY3t6l-vDxPnQX5rnKDTGG4',
    appId: '1:316719139611:web:004adfbdd1adf977bea1be',
    messagingSenderId: '316719139611',
    projectId: 'chatoo-f8ba5',
    authDomain: 'chatoo-f8ba5.firebaseapp.com',
    storageBucket: 'chatoo-f8ba5.appspot.com',
    measurementId: 'G-NKB2JEW3DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VEdiQfzY4KAsJkdl9LQs4mZ4oZ2JH6I',
    appId: '1:316719139611:android:4732c166d7a117e9bea1be',
    messagingSenderId: '316719139611',
    projectId: 'chatoo-f8ba5',
    storageBucket: 'chatoo-f8ba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv4wp4x0NH4axo43aiDjE8Xc-5Fq6zYsM',
    appId: '1:316719139611:ios:4eacc257cea77e10bea1be',
    messagingSenderId: '316719139611',
    projectId: 'chatoo-f8ba5',
    storageBucket: 'chatoo-f8ba5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
